### ISSUE TITLE
[V3-RC4] PIXI.TilingSprite Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by nylira** [GoodBoyDigital/pixi.js#1593]
I'm using pixi.js 3.0.0-rc4 with browserify and trying to draw a TilingSprite for my world background. pixi.js doesn't seem to be locating the TilingSprite function.

**Comment by nylira** [comment]
The TilingSprite did used to work on previous 3.0.0 release candidates, but I run into an error with the ResourceLoader if I downgrade to 3.0.0-rc3 or below and refresh my project:

    this.use(ResourceLoader.middleware.parsing.json())

(loader.js:30)

**Comment by drkibitz** [comment]
TilingSprite is now namespaced here, `PIXI.extras.TilingSprite`.
For more information see details on this release:
https://github.com/GoodBoyDigital/pixi.js/releases/tag/v3.0.0-rc4

docs:
http://pixijs.github.io/docs/
http://pixijs.github.io/docs/PIXI.extras.TilingSprite.html

and these issues:
https://github.com/GoodBoyDigital/pixi.js/issues/1588
https://github.com/GoodBoyDigital/pixi.js/issues/1565
https://github.com/GoodBoyDigital/pixi.js/pull/1478

---

Resource loader is an npm dependency, be sure you downgrade that along with pixi itself. If you have, @englercj might have more info. Hopefully just changing to the namespaced TilingSprite should work.

**Comment by nylira** [comment]
Thanks, changing to the namedspaced TilingSprite worked.

Thanks for the links to those docs too. I haven't seen that page before. All I knew was that these pages were outdated for 3.0: http://www.goodboydigital.com/pixijs/docs/

**Comment by drkibitz** [comment]
Thar be new docs ;)
Just saw myself in a post by @englercj 

Just to note, if you have the source cloned and building...
you can always build the docs too with `npm run docs && open docs/index.html`
