### ISSUE TITLE
What is the preferred method to consume PIXI.js in a project via Browserify?

### ISSUE THREAD

**Issue by baseten** [GoodBoyDigital/pixi.js#1548]
Apologies, not an issue with PIXI.js as such, but I'm having a bit of trouble compiling PIXI.js into a project using Browserify, I'm working with v3.0.0-rc2. If there's a better place for me to post this please let me know.

I've installed PIXI via bower: `bower install https://github.com/GoodBoyDigital/pixi.js.git#v3.0.0-rc2` if I try to compile in the non-minified build (`pixi.js/bin/pixi.js`) with Browserify I get the error `Cannot find module './Resource'`. I can compile PIXI again from src, which seems to work, but I have to make sure to do an `npm install` inside the `pixi.js` folder first (at which point it looks like I'm installing a few things that already exist in my project's `node_modules`)

**Comment by englercj** [comment]
Install pixi.js via npm not via bower. Then just do `require('pixi.js')`.

One of the biggest benefits of browserify is the ability to work seamlessly with npm.

**Comment by baseten** [comment]
Seems obvious now! Thank you
